name: CI
on: [push, pull_request]
jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    script:
      - apt-get update && apt-get install -y gawk
      - npm install
      - npm install -g truffle
      - npm install -g ganache-cli
      - sleep 5
      - truffle migrate
      - truffle test
      - npm run stop    
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
   