name: CI
on: [push, pull_request]
jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
      - name: run ganache
        run: ./node_modules/ganache-cli/cli.js -p 8545 
      - name: Migrate Contracts
        run: ./node_modules/truffle/build/cli.bundled.js migrate --network development
      - name: Test Contracts
        run: ./node_modules/truffle/build/cli.bundled.js test --network development
      - name: Stop ganache
        run: kill $(lsof -t -i:8545)  
        