name: CI
on: [push, pull_request]
jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
      - name: Install truffle 
        run: npm install -g truffle 
      - name: Install Ganache 
        run: npm install -g ganache-cli 
        
      # - name: Start Ganache 
      #   run: truffle develop
      # - name: Migrate contract 
      #   run: truffle migrate
      # - name: Truffle Test
      #   run: truffle test --watchAll=false




      - name: Start ganache
        run: |
        ./node_modules/ganache-cli/cli.js -p 8545 --gasLimit=0x1fffffffffffff --allowUnlimitedContractSize -e 1000000000 > /dev/null &
        while netstat -lnt | awk '$4 ~ /:8545$/ {exit 1}'; do sleep 5; done
      - name: Migrate Contracts
        run: ./node_modules/truffle/build/cli.bundled.js migrate --network development
      - name: Test Contracts
        run: ./node_modules/truffle/build/cli.bundled.js test --network development
      - name: Stop ganache
        run: kill $(lsof -t -i:8545)
        

