name: CI
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
      
      - name: Install truffle 
        run: npm install -g truffle 
    
      - name: Install Ganache 
        run: npm install -g ganache-cli 

      - run: /usr/local/lib//node_modules/ganache-cli/cli.js -p 8545 --gasLimit=0x1fffffffffffff --allowUnlimitedContractSize -e 1000000000 > /dev/null &
        while netstat -lnt | awk '$4 ~ /:8545$/ {exit 1}';


  build: 
    needs: setup
    runs-on: ubuntu-latest
    steps: 
      - name: Migrate contract 
        run: truffle migrate
     
      - name: Truffle Test
        run: truffle test --watchAll=false
     
      - name: Migrate Contracts
        run: ./node_modules/truffle/build/cli.bundled.js migrate --network development
 
  
  shutdown:
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Stop ganache
        run: kill $(lsof -t -i:9545)
      

