name: CI
on: [push, pull_request]
jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
      - name: Truffle Test
        run: truffle test --watchAll=false
        