name: CI
on: [push, pull_request]
jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Set up NodeJS 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Cache npm packages
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install npm packages
        run: yarn

      - name: Install truffle 
        run: npm install -g truffle 
    
      - name: Install Ganache 
        run: npm install -g ganache-cli
  
        job1: |
          ./node_modules/ganache-cli/cli.js -p 9545 --gasLimit=0x1fffffffffffff --allowUnlimitedContractSize -e 1000000000 > /dev/null &
          while netstat -lnt | awk '$4 ~ /:9545$/ {exit 1}'; do sleep 5; done ; 


        job2: ./node_modules/truffle/build/cli.bundled.js migrate --network development
        needs: job1

        job3:
        needs: [job1, job2]             
      
      - name: Start ganache
        run: |
          ./node_modules/ganache-cli/cli.js -p 9545 --gasLimit=0x1fffffffffffff --allowUnlimitedContractSize -e 1000000000 > /dev/null &
          while netstat -lnt | awk '$4 ~ /:9545$/ {exit 1}'; do sleep 5; done ;kill $(lsof -t -i:9545)
          steps.timeout-minutes: 1 

      
      
      - name: Migrate Contracts
        run: ./node_modules/truffle/build/cli.bundled.js migrate --network development


      - name: Test Contracts
        run: ./node_modules/truffle/build/cli.bundled.js test --network development
      
      
      - name: Stop ganache
        run: kill $(lsof -t -i:9545)

        
      
      
      # - uses: actions/checkout@v1
      
      # - name: Install Dependencies
      #   run: yarn
      
      # - name: Install truffle 
      #   run: npm install -g truffle 
    
      # - name: Install Ganache 
      #   run: npm install -g ganache-cli

      # - name: Start ganache
      #   run:  /usr/local/lib//node_modules/ganache-cli/cli.js -p 8545 --gasLimit=0x1fffffffffffff --allowUnlimitedContractSize -e 1000000000 > /dev/null &
      #   while netstat -lnt | awk '$4 ~ /:8545$/ {exit 1}  do sleep 5; done';

      # - name: Migrate Contracts
      #   run: ./node_modules/truffle/build/cli.bundled.js migrate --network development

      # - name: Test Contracts
      #   run: ./node_modules/truffle/build/cli.bundled.js test --network development

      # - name: Stop ganache
      #   run: kill $(lsof -t -i:8545)
        

      # - name: Start Ganache 
      #   run: truffle develop
      # - name: Migrate contract 
      #   run: truffle migrate
      # - name: Truffle Test
      #   run: truffle test --watchAll=false
