name: CI
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
      
      - name: Install truffle 
        run: npm install -g truffle 
    
      - name: Install Ganache 
        run: npm install -g ganache-cli 

      - run: truffle develop


  build: 
    needs: setup
    runs-on: ubuntu-latest
    steps: 
      - name: Migrate contract 
        run: truffle migrate
      - name: Truffle Test
        run: truffle test --watchAll=false
  
  # shutdown:

