name: CI
on: [push, pull_request]
jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: yarn
      - name: Install truffle 
        run: npm install -g truffle 
      - name: Install Ganache 
        run: npm install -g ganache-cli 
      - name: Start Ganache 
        run: truffle develop
      - name: Migrate contract 
        run: truffle migrate
      - name: Truffle Test
        run: truffle test --watchAll=false
        

